"""add cluster column

Revision ID: bd3c71516b3b
Revises: eff0a26ef262
Create Date: 2026-06-30 17:54:43.209198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd3c71516b3b'
down_revision: Union[str, None] = 'eff0a26ef262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cluster', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_cluster'), 'products', ['cluster'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_cluster'), table_name='products')
    op.drop_column('products', 'cluster')
    op.create_table('produk',
    sa.Column('COL 1', mysql.VARCHAR(length=309), nullable=True),
    sa.Column('COL 2', mysql.VARCHAR(length=318), nullable=True),
    sa.Column('COL 3', mysql.VARCHAR(length=182), nullable=True),
    sa.Column('COL 4', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('COL 5', mysql.VARCHAR(length=84), nullable=True),
    sa.Column('COL 6', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('COL 7', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('COL 8', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('COL 9', mysql.VARCHAR(length=10), nullable=True),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
