from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd8e665f18a'
down_revision: Union[str, None] = 'd6e3f6de4022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('needs_retrain', sa.Boolean(), nullable=True),
    sa.Column('last_trained_at', sa.DateTime(), nullable=True),
    sa.Column('last_dataset_update', sa.DateTime(), nullable=True),
    sa.Column('model_status', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_status_id'), 'ml_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_status_id'), table_name='ml_status')
    op.drop_table('ml_status')
    # ### end Alembic commands ###
